### PR TITLE
Allow specification of separate authentication and view server URLs

### PR DESCRIPTION
**Pull request by rbergen**
Allows two URLs to be specified, either through configuration or initialization options:
- One via which the actual Trusted Authentication towards Tableau takes place
- Another one from which the applicable views are retrieved by the user's browser

For both the configuration and initialization scenarios, the existing default_server/server option can be used as a fallback for each of the individual URLs. 

This change supports scenarios like those where Trusted Authentication needs to take place using an "internal" Tableau hostname/IP address (& scheme), while the resulting views need to be retrieved via an "external" DNS name (& scheme).

### CODE REVIEW

**Comment by hughevans** [comment]
Thanks for this @rbergen! I will review, merge and publish on the weekend.

From your experience using the library are there any dependencies that I should be looking to update?

**Comment by rbergen** [comment]
Hi @hughevans, you're very welcome. Your gem has been very helpful for us, so I'm happy to be able to give something back. I trust you will let me know if any questions arise while reviewing, and such.

I have forwarded your question concerning dependencies to the developers in my team who use the gem most, and they came back with the following dependency recommendation, based on our usage:
```
'rspec', ['>= 3.4', '<= 3.9']
'vcr', ['>= 3.0', '<= 4.0']
'webmock', ['>= 1.22', '< 3.4.3']
'activesupport', ['>= 3.0', '< 5.2']
'addressable', ['~> 2.3', '~> 2.5']
'rest-client', ['>= 1.6', '<= 2.1']
```

**Comment by rbergen** [comment]
I've created a version of the gemspec that incorporates the dependency versioning that I mentioned in my previous comment. If you want me to commit it so it's included in this PR, just let me know.

**Comment by hughevans** [comment]
Thanks @rbergen, I’ve merged in #3 and pushed `2.0.0` to Rubygems.

**Pull request closed without merging**
